export const one = [
  "public/poster/cards/Item-01.png",
  "public/poster/cards/item-02.png",
  "public/poster/cards/item-03.png",
  "public/poster/cards/item-04.png",
  "public/poster/cards/item-05.png",
  "public/poster/cards/item-06.png",
  "public/poster/cards/item-07.png",
  "public/poster/cards/item-08.png",
  "public/poster/cards/item-09.png",
  "public/poster/cards/item-10.png",
  "public/poster/cards/item-11.png",
  "public/poster/cards/item-12.png",
];

export const two = [
  "/poster/01.webp",
  "/poster/02.jpeg",
  "/poster/03.webp",
  "/poster/04.webp",
  "/poster/05.webp",
  "/poster/06.jpeg",
  // "/poster/cards/item-06.png",
  // "/poster/cards/item-07.png",
  // "/poster/cards/item-08.png",
  // "/poster/cards/item-09.png",
  // "/poster/cards/item-10.png",
  // "/poster/cards/item-11.png",
  // "/poster/cards/item-12.png",
];
